### ISSUE TITLE
Support for persisted queries?

### ISSUE THREAD

**Issue by shmax** [firede/ts-transform-graphql-tag#16]
Hi there, I love the functionality of this loader, but rather than replace an inline query with its AST, I would rather generate a hash from the query, replace the inline query with the hash, and write the hash along with the generated AST to a file that my back end can later use to look up a query. Is that something I can do with this package? Does it make sense? If it does, would you welcome a PR?

Also, I'm curious about your statement:

> Because I moved to @babel/preset-typescript from typescript, this package is no longer maintained.

What does that mean, exactly? Do you mean that you moved to babel from webpack? How are you accomplishing the functionality in this package with babel? 

Thanks very much for your support.

**Comment by firede** [comment]
Hi there.

> Does it make sense? If it does, would you welcome a PR?

This feature is beyond the scope of `transformer`, I think it is more appropriate to create a separate library.

> Do you mean that you moved to babel from webpack?

In fact, many popular libraries now uses babel to [handle TypeScript](https://babeljs.io/docs/en/babel-preset-typescript), such as [create-react-app](https://create-react-app.dev/docs/adding-typescript/#troubleshooting), [next.js](https://nextjs.org/docs/basic-features/typescript), etc.

Therefore, many plugins support the babel version first. It seems a bit expensive to make a TypeScript version with the same function.

> How are you accomplishing the functionality in this package with babel?

You can use [`babel-plugin-graphql-tag`](https://github.com/gajus/babel-plugin-graphql-tag) as an alternative.

**Comment by shmax** [comment]
> This feature is beyond the scope of transformer, I think it is more appropriate to create a separate library.

Maybe, but the new library would share 95% of its code with your code. I have a rough prototype working, and all I really had to do was modify a few lines. But since there's only a few pages of code involved here either way I won't bother opening a PR or making a new library, especially if you've moved on to greener pastures.

> Therefore, many plugins support the babel version first. It seems a bit expensive to make a TypeScript version with the same function.

I'm not too familiar with Babel, but if I understand correctly, we have this kind of flow...

1. Write your code in Typescript (including `gql` tags)
2. On every build, babel compiles all the typescript to raw javascript
3. Now that everything is in javascript, `babel-plugin-graphql-tag` does a pass and replaces those `gql` literals with AST objects.

Do I have that right? If so, it certainly sounds promising, especially given that [awesome-typescript-loader](https://github.com/s-panferov/awesome-typescript-loader) seems to have fallen into disrepair. 

I guess I'll have to look into that for my next big project. Thank you kindly for your support. 👍

**Comment by shmax** [comment]
Just wanted to let you know that I took your suggestion and moved to @babel/preset-typescript from awesome-typescript-loader, and that did indeed open a world of new possibilities. Thanks much for the great advice. Closing.
